// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Data;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(PalleOptimeringContext))]
    partial class PalleOptimeringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyProject.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Bredde")
                        .HasColumnType("int");

                    b.Property<int>("Dybde")
                        .HasColumnType("int");

                    b.Property<bool>("ErGeometrielement")
                        .HasColumnType("bit");

                    b.Property<bool>("ErSpecialelement")
                        .HasColumnType("bit");

                    b.Property<int>("Hoejde")
                        .HasColumnType("int");

                    b.Property<string>("KraeverPalletype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Maerke")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaksElementerPrPalle")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RotationsRegel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Serie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Vaegt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Elementer");
                });

            modelBuilder.Entity("MyProject.Models.Pakkeplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AntalElementer")
                        .HasColumnType("int");

                    b.Property<int>("AntalPaller")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oprettet")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrdreReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SettingsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.ToTable("Pakkeplaner");
                });

            modelBuilder.Entity("MyProject.Models.PakkeplanElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<bool>("ErRoteret")
                        .HasColumnType("bit");

                    b.Property<int>("Lag")
                        .HasColumnType("int");

                    b.Property<int>("PakkeplanPalleId")
                        .HasColumnType("int");

                    b.Property<int>("Plads")
                        .HasColumnType("int");

                    b.Property<int>("Sortering")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("PakkeplanPalleId");

                    b.ToTable("PakkeplanElementer");
                });

            modelBuilder.Entity("MyProject.Models.PakkeplanPalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AntalLag")
                        .HasColumnType("int");

                    b.Property<int>("PakkeplanId")
                        .HasColumnType("int");

                    b.Property<int>("PalleId")
                        .HasColumnType("int");

                    b.Property<int>("PalleNummer")
                        .HasColumnType("int");

                    b.Property<int>("SamletHoejde")
                        .HasColumnType("int");

                    b.Property<decimal>("SamletVaegt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PakkeplanId");

                    b.HasIndex("PalleId");

                    b.ToTable("PakkeplanPaller");
                });

            modelBuilder.Entity("MyProject.Models.Palle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<int>("Bredde")
                        .HasColumnType("int");

                    b.Property<int>("Hoejde")
                        .HasColumnType("int");

                    b.Property<int>("Laengde")
                        .HasColumnType("int");

                    b.Property<int>("LuftMellemElementer")
                        .HasColumnType("int");

                    b.Property<int>("MaksHoejde")
                        .HasColumnType("int");

                    b.Property<decimal>("MaksVaegt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Overmaal")
                        .HasColumnType("int");

                    b.Property<string>("PalleBeskrivelse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pallegruppe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Palletype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sortering")
                        .HasColumnType("int");

                    b.Property<decimal>("Vaegt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Paller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktiv = true,
                            Bredde = 750,
                            Hoejde = 150,
                            Laengde = 2400,
                            LuftMellemElementer = 10,
                            MaksHoejde = 2800,
                            MaksVaegt = 1000m,
                            Overmaal = 50,
                            PalleBeskrivelse = "75'er Træpalle",
                            Pallegruppe = "75",
                            Palletype = "Trae",
                            Sortering = 1,
                            Vaegt = 25m
                        },
                        new
                        {
                            Id = 2,
                            Aktiv = true,
                            Bredde = 800,
                            Hoejde = 150,
                            Laengde = 2400,
                            LuftMellemElementer = 10,
                            MaksHoejde = 2800,
                            MaksVaegt = 1200m,
                            Overmaal = 50,
                            PalleBeskrivelse = "80'er Træpalle",
                            Pallegruppe = "80",
                            Palletype = "Trae",
                            Sortering = 2,
                            Vaegt = 27m
                        },
                        new
                        {
                            Id = 3,
                            Aktiv = true,
                            Bredde = 1000,
                            Hoejde = 150,
                            Laengde = 2400,
                            LuftMellemElementer = 10,
                            MaksHoejde = 2800,
                            MaksVaegt = 1500m,
                            Overmaal = 50,
                            PalleBeskrivelse = "100'er Træpalle",
                            Pallegruppe = "100",
                            Palletype = "Trae",
                            Sortering = 3,
                            Vaegt = 30m
                        });
                });

            modelBuilder.Entity("MyProject.Models.PalleOptimeringSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<decimal>("HoejdeBreddefaktor")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("HoejdeBreddefaktorKunForEnkeltElementer")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaksBalanceVaerdi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaksLag")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PlacerLaengsteElementerYderst")
                        .HasColumnType("bit");

                    b.Property<string>("SorteringsPrioritering")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("TilladStablingOpTilMaksElementVaegt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TilladStablingOpTilMaksHoejdeInklPalle")
                        .HasColumnType("int");

                    b.Property<decimal>("TilladVendeOpTilMaksKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TillaegMonteringAfEndeplade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktiv = true,
                            HoejdeBreddefaktor = 0.3m,
                            HoejdeBreddefaktorKunForEnkeltElementer = true,
                            MaksBalanceVaerdi = 100m,
                            MaksLag = 2,
                            Navn = "Standard",
                            PlacerLaengsteElementerYderst = true,
                            SorteringsPrioritering = "Maerke,Specialelement,Pallestorrelse,Elementstorrelse,Vaegt,Serie",
                            TilladStablingOpTilMaksElementVaegt = 70m,
                            TilladStablingOpTilMaksHoejdeInklPalle = 1500,
                            TilladVendeOpTilMaksKg = 50m,
                            TillaegMonteringAfEndeplade = 20
                        });
                });

            modelBuilder.Entity("MyProject.Models.Pakkeplan", b =>
                {
                    b.HasOne("MyProject.Models.PalleOptimeringSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("MyProject.Models.PakkeplanElement", b =>
                {
                    b.HasOne("MyProject.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.Models.PakkeplanPalle", "PakkeplanPalle")
                        .WithMany("Elementer")
                        .HasForeignKey("PakkeplanPalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("PakkeplanPalle");
                });

            modelBuilder.Entity("MyProject.Models.PakkeplanPalle", b =>
                {
                    b.HasOne("MyProject.Models.Pakkeplan", "Pakkeplan")
                        .WithMany("Paller")
                        .HasForeignKey("PakkeplanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.Models.Palle", "Palle")
                        .WithMany()
                        .HasForeignKey("PalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pakkeplan");

                    b.Navigation("Palle");
                });

            modelBuilder.Entity("MyProject.Models.Pakkeplan", b =>
                {
                    b.Navigation("Paller");
                });

            modelBuilder.Entity("MyProject.Models.PakkeplanPalle", b =>
                {
                    b.Navigation("Elementer");
                });
#pragma warning restore 612, 618
        }
    }
}
